# Generated by Django 5.2.3 on 2025-07-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trangvang_crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawltask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('WARNING', 'Warning')], default='PENDING', max_length=20),
        ),
    ]
